#!/usr/bin/env perl
#
# net2loc
#
# Gets a list of stations, one per line for a network, or networks
# and lists them 
#
# Rod Stewart, 2009-07-24

my @nets = @ARGV;

@stas = `./net2sta @nets`;
chomp( @stas );

foreach $sta (@stas) {
	@locs = `./sta2loc $sta`;
	chomp( @locs );
	foreach $loc (@locs) {
		print $loc, "\n";
	}
}
