#!/usr/bin/env perl
#
# sta2loc
#
# Gets a list of stations as arguments and
# and lists all the locations
#
# Rod Stewart, 2009-07-24

my @stas = @ARGV;

foreach $sta (@stas) {
	open( FH, 'data/locations.txt');
	@lines = grep /^$sta/, <FH>;
	close( FH );
	chomp @lines;
	foreach $line (@lines) {
		print $line, "\n";
	}
}
