#!/usr/bin/env perl
#
# stastatus
#
# Gets a list of stations as arguments and
# and lists all the status info
#
# Rod Stewart, 2009-07-24

my @stas = @ARGV;

foreach $sta (@stas) {
	open( FH, 'data/status.txt');
	@lines = grep /^$sta/, <FH>;
	close( FH );
	chomp @lines;
	foreach $line (@lines) {
		print $line, "\n";
	}
}
